const AllpurchestableData = [
    {
        checked : false,
        id:1,
        RefNo : "PO9868",
        MaskingName : "",
        PoType : "retail",
        Marchent : "EAST LINE",
        Suppiler : "Husnain",
        Qty : "570",
        Dmg : "0",
        Miss : "0",
        Rec : "0",
        RsDmg : "Rs 0",
        RsMiss : "Rs 0",
        Status : "Budget Approval",
        PreOrder : "No",
        Payment : "Pending",
        GrandTotal : "1,069",
        Action : "Action",
    },
    {
        checked : false,
        id:2,
        RefNo : "PO9869",
        MaskingName : "",
        PoType : "retail",
        Marchent : "EAST LINE",
        Suppiler : "Husnain",
        Qty : "570",
        Dmg : "0",
        Miss : "0",
        Rec : "0",
        RsDmg : "Rs 0",
        RsMiss : "Rs 0",
        Status : "Budget Approval",
        PreOrder : "No",
        Payment : "Pending",
        GrandTotal : "1,069",
        Action : "Action",
    },
    {
        checked : false,
        id:3,
        RefNo : "PO9870",
        MaskingName : "",
        PoType : "retail",
        Marchent : "EAST LINE",
        Suppiler : "Husnain",
        Qty : "570",
        Dmg : "0",
        Miss : "0",
        Rec : "0",
        RsDmg : "Rs 0",
        RsMiss : "Rs 0",
        Status : "Budget Approval",
        PreOrder : "No",
        Payment : "Pending",
        GrandTotal : "1,069",
        Action : "Action",
    },
    // {
    //     checked : false,
    //     id:4,
    //     RefNo : "PO9871",
    //     MaskingName : "",
    //     PoType : "retail",
    //     Marchent : "EAST LINE",
    //     Suppiler : "Husnain",
    //     Qty : "570",
    //     Dmg : "0",
    //     Miss : "0",
    //     Rec : "0",
    //     RsDmg : "Rs 0",
    //     RsMiss : "Rs 0",
    //     Status : "Budget Approval",
    //     PreOrder : "No",
    //     Payment : "Pending",
    //     GrandTotal : "1,069",
    //     Action : "Action",
    // },
    
];
export default AllpurchestableData;